### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by rogargon**
Dockerization proposal including PHP Apache image

### CODE REVIEW

**Comment by rogargon** [comment]
To run locally including deployment of MariaDB initialized with `sql-files/schema.sql`:

```bash
docker-compose up -d --build
``` 

After image building and deployment, application should be available at `http://localhost:8080`

NOTE: requires Docker, https://docs.docker.com/install/

**Comment by rogargon** [comment]
Missing SQL files for database initialization so currently no default users or content like "about-us". Also missing way to configure SMTP.

**Comment by atgrau** [comment]
There's a config file named _global.php_ placed at: **/src/config/global.php** with the following content (not added to git repository, cuz it has a sensitive data):

```
<?php
  # Do not show notice errors
  error_reporting(E_ALL & ~E_NOTICE);
  //error_reporting(~E_ALL);

  define("APP_TITLE", "Heuristic Evaluation Tool");
  define("URL", "http://vps570954.ovh.net:85/");
  define("EMAIL", "heuristicevaluationudl@gmail.com");

  // Email Configuration
  define("SMTP_SERVER", "smtp.domain.com");
  define("SMTP_PORT", 587);
  define("SMTP_USER", "USER@DOMAIN.COM");
  define("SMTP_PASSWORD", "PASSWORD");
  define("SMTP_SECURE", "tls");
  define("SMTP_AUTH", true);
  define("SMTP_NAME", "Heuristic Evaluation Tool");
  define("SMTP_FROM", "heuristicevaluationudl@gmail.com");
?>

**Comment by atgrau** [comment]
> Missing SQL files for database initialization so currently no default users or **content like "about-us"**. Also missing way to configure SMTP.

image

ID -> Key
Content -> Dynamic HTML content

**Pull request merged**
